security:
  oauth2:
    client:
      clientId: 390101475470-hq59sq3a4liootmhibuc2egghlua0ioe.apps.googleusercontent.com
      clientSecret: ${oAuthKey}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
server:
  port: 8080
  session:
    timeout: 0